# Generated by Django 6.0.6 on 2026-08-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_number', models.IntegerField()),
                ('patient_issue', models.CharField(max_length=200)),
                ('appointment_date', models.DateTimeField()),
            ],
        ),
    ]
