# Generated by Django 6.0.6 on 2026-08-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
